name: tg-docker-heroku CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
#set environment variables 
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'tg-bot-docker' }}
  TELEGRAM_API_ID: ${{ '17537141' }}
  TELEGRAM_API_HASH: ${{ 'e6de5065e2d3747a93e88ce53db05170' }}

jobs:
      
  deploy:
    name: Deploy to Heroku
    runs-on: alpine
    steps:

    # Clone the repository
    - name: Checkout
      uses: actions/checkout@v2

    # Build Docker image
    - name: Docker build
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # Push the Docker image to Heroku Container Registry
    - name: Publish
      run: |
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
